apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
  namespace: uplanner
  labels:
    app: uplanner-rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uplanner-rng
  template:
    metadata:
      labels:
        app: uplanner-rng
    spec:
      containers:
        - name: uplanner-rng-app
          image: uplanner/rng:v2
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
